// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PatternPro.DataAccess.Persistence;

#nullable disable

namespace PatternPro.DataAccess.Migrations
{
    [DbContext(typeof(PatternProDbContext))]
    [Migration("20260615053340_AddAppUsers")]
    partial class AddAppUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pattern.Core.Model.Pattern", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("ApprovedForCutting")
                        .HasColumnType("boolean");

                    b.Property<string>("BaseSize")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("CloReviewCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("CloReviewNotes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CutterTestNotes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("CutterTestPassed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CutterTestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CutterTestedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Designer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FabricStretchPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("PieceCount")
                        .HasColumnType("integer");

                    b.Property<string>("Revision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("ShrinkagePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("patterns", "patternpro");
                });

            modelBuilder.Entity("PatternPro.DataAccess.Persistence.AppKeyValue", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("app_kv", "patternpro");
                });

            modelBuilder.Entity("PatternPro.DataAccess.Persistence.AppUserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("app_users", "patternpro");
                });

            modelBuilder.Entity("PatternPro.DataAccess.Persistence.EaseOverrideEntity", b =>
                {
                    b.Property<string>("StyleKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MeasurementPoint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("StyleKey", "MeasurementPoint");

                    b.ToTable("ease_overrides", "patternpro");
                });

            modelBuilder.Entity("PatternPro.DataAccess.Persistence.GradingColumnEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder")
                        .IsUnique();

                    b.ToTable("grading_columns", "patternpro");
                });

            modelBuilder.Entity("PatternPro.DataAccess.Persistence.GradingDeltaEntity", b =>
                {
                    b.Property<int>("RowId")
                        .HasColumnType("integer");

                    b.Property<int>("ColumnIndex")
                        .HasColumnType("integer");

                    b.Property<double>("Delta")
                        .HasColumnType("double precision");

                    b.HasKey("RowId", "ColumnIndex");

                    b.ToTable("grading_deltas", "patternpro");
                });

            modelBuilder.Entity("PatternPro.DataAccess.Persistence.GradingMetaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("grading_meta", "patternpro");
                });

            modelBuilder.Entity("PatternPro.DataAccess.Persistence.GradingRowEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseIndex")
                        .HasColumnType("integer");

                    b.Property<string>("MeasurementPoint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StyleKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("StyleKey", "MeasurementPoint")
                        .IsUnique();

                    b.ToTable("grading_rows", "patternpro");
                });

            modelBuilder.Entity("PatternPro.DataAccess.Persistence.GradingStyleEntity", b =>
                {
                    b.Property<string>("StyleKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("StyleKey");

                    b.ToTable("grading_styles", "patternpro");
                });

            modelBuilder.Entity("PatternPro.DataAccess.Persistence.MeasurementProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("measurement_profiles", "patternpro");
                });

            modelBuilder.Entity("PatternPro.DataAccess.Persistence.MeasurementProfileValueEntity", b =>
                {
                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("MeasurementPoint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("ProfileId", "MeasurementPoint");

                    b.ToTable("measurement_profile_values", "patternpro");
                });

            modelBuilder.Entity("PatternPro.DataAccess.Persistence.PieceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Cut")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GrainLine")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("OffsetX")
                        .HasColumnType("integer");

                    b.Property<int>("OffsetY")
                        .HasColumnType("integer");

                    b.Property<bool>("OnFold")
                        .HasColumnType("boolean");

                    b.Property<int?>("PatternId")
                        .HasColumnType("integer");

                    b.Property<string>("PieceNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("PieceOrder")
                        .HasColumnType("integer");

                    b.Property<double>("SeamAllowance")
                        .HasColumnType("double precision");

                    b.Property<string>("SeamAllowanceJoin")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("StyleKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("PatternId");

                    b.HasIndex("StyleKey");

                    b.ToTable("pieces", "patternpro");
                });

            modelBuilder.Entity("PatternPro.DataAccess.Persistence.PieceVertexEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("PieceId")
                        .HasColumnType("integer");

                    b.Property<int>("PointOrder")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PieceId", "Kind", "PointOrder");

                    b.ToTable("piece_vertices", "patternpro");
                });

            modelBuilder.Entity("PatternPro.DataAccess.Persistence.SizeChartColumnEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder")
                        .IsUnique();

                    b.ToTable("size_chart_columns", "patternpro");
                });

            modelBuilder.Entity("PatternPro.DataAccess.Persistence.SizeChartRowEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MeasurementMethod")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("MeasurementPoint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<decimal>("ToleranceCm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder")
                        .IsUnique();

                    b.ToTable("size_chart_rows", "patternpro");
                });

            modelBuilder.Entity("PatternPro.DataAccess.Persistence.SizeChartValueEntity", b =>
                {
                    b.Property<int>("RowId")
                        .HasColumnType("integer");

                    b.Property<int>("ColumnIndex")
                        .HasColumnType("integer");

                    b.Property<int?>("SizeChartColumnEntityId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("RowId", "ColumnIndex");

                    b.HasIndex("SizeChartColumnEntityId");

                    b.ToTable("size_chart_values", "patternpro");
                });

            modelBuilder.Entity("PatternPro.DataAccess.Persistence.GradingDeltaEntity", b =>
                {
                    b.HasOne("PatternPro.DataAccess.Persistence.GradingRowEntity", "Row")
                        .WithMany("Deltas")
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Row");
                });

            modelBuilder.Entity("PatternPro.DataAccess.Persistence.GradingRowEntity", b =>
                {
                    b.HasOne("PatternPro.DataAccess.Persistence.GradingStyleEntity", "Style")
                        .WithMany("Rows")
                        .HasForeignKey("StyleKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Style");
                });

            modelBuilder.Entity("PatternPro.DataAccess.Persistence.MeasurementProfileValueEntity", b =>
                {
                    b.HasOne("PatternPro.DataAccess.Persistence.MeasurementProfileEntity", "Profile")
                        .WithMany("Values")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("PatternPro.DataAccess.Persistence.PieceVertexEntity", b =>
                {
                    b.HasOne("PatternPro.DataAccess.Persistence.PieceEntity", "Piece")
                        .WithMany("Vertices")
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Piece");
                });

            modelBuilder.Entity("PatternPro.DataAccess.Persistence.SizeChartValueEntity", b =>
                {
                    b.HasOne("PatternPro.DataAccess.Persistence.SizeChartRowEntity", "Row")
                        .WithMany("Values")
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatternPro.DataAccess.Persistence.SizeChartColumnEntity", null)
                        .WithMany("Values")
                        .HasForeignKey("SizeChartColumnEntityId");

                    b.Navigation("Row");
                });

            modelBuilder.Entity("PatternPro.DataAccess.Persistence.GradingRowEntity", b =>
                {
                    b.Navigation("Deltas");
                });

            modelBuilder.Entity("PatternPro.DataAccess.Persistence.GradingStyleEntity", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("PatternPro.DataAccess.Persistence.MeasurementProfileEntity", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("PatternPro.DataAccess.Persistence.PieceEntity", b =>
                {
                    b.Navigation("Vertices");
                });

            modelBuilder.Entity("PatternPro.DataAccess.Persistence.SizeChartColumnEntity", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("PatternPro.DataAccess.Persistence.SizeChartRowEntity", b =>
                {
                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
