<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Pattern.Web</RootNamespace>
    <AssemblyName>Pattern.Web</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pattern.Web.Model\Pattern.Web.Model.csproj" />
    <ProjectReference Include="..\Pattern.PublicServices\Pattern.PublicServices.csproj" />
    <ProjectReference Include="..\Pattern.Core.Model\Pattern.Core.Model.csproj" />
  </ItemGroup>

</Project>
